{
    "id": "LUCENE-5600",
    "title": "HttpReplicator does not properly handle server failures",
    "details": {
        "type": "Bug",
        "priority": "Major",
        "labels": "",
        "resolution": "Fixed",
        "components": [
            "modules/replicator"
        ],
        "affect_versions": "4.7.1",
        "status": "Resolved",
        "fix_versions": [
            "4.8.1",
            "4.9",
            "6.0"
        ]
    },
    "description": "When ReplicationClient.updateNow() using an HttpReplicator encounters a server error (like Status Code 500), it throws a runtime exception instead of an IOException.\nFurthermore, it does not close the HttpClient it used, which leads to an Error if a BasicClientConnectionManager is used",
    "attachments": {
        "HttpReplicatorTest.patch": "https://issues.apache.org/jira/secure/attachment/12639775/HttpReplicatorTest.patch",
        "HttpClientBase-LUCENE-5600.java.patch": "https://issues.apache.org/jira/secure/attachment/12639776/HttpClientBase-LUCENE-5600.java.patch",
        "LUCENE-5600.patch": "https://issues.apache.org/jira/secure/attachment/12640607/LUCENE-5600.patch"
    },
    "issue_links": {},
    "comments": [
        {
            "id": "comment-13966383",
            "author": "Christoph Kaser",
            "content": "Test ",
            "date": "2014-04-11T10:26:54+0000"
        },
        {
            "id": "comment-13966385",
            "author": "Christoph Kaser",
            "content": "Fix ",
            "date": "2014-04-11T10:28:44+0000"
        },
        {
            "id": "comment-13972812",
            "author": "Shai Erera",
            "content": "I applied the patch, cleaned up few things and added CHANGES. I didn't apply the part which guarantees to throw IOException always, we should be prepared to handle RuntimeExceptions and Errors too. I think it's ready, but will wait some before commit. ",
            "date": "2014-04-17T10:13:05+0000"
        },
        {
            "id": "comment-13973098",
            "author": "ASF subversion and git services",
            "content": "Commit 1588296 from shaie@apache.org in branch 'dev/trunk'\n[ https://svn.apache.org/r1588296 ]\n\nLUCENE-5600: HttpReplicator does not properly handle server failures ",
            "date": "2014-04-17T16:06:42+0000"
        },
        {
            "id": "comment-13973100",
            "author": "ASF subversion and git services",
            "content": "Commit 1588297 from shaie@apache.org in branch 'dev/branches/branch_4x'\n[ https://svn.apache.org/r1588297 ]\n\nLUCENE-5600: HttpReplicator does not properly handle server failures ",
            "date": "2014-04-17T16:09:27+0000"
        },
        {
            "id": "comment-13973101",
            "author": "Shai Erera",
            "content": "Committed to trunk and 4x. Thanks Christoph! ",
            "date": "2014-04-17T16:09:59+0000"
        },
        {
            "id": "comment-13989757",
            "author": "ASF subversion and git services",
            "content": "Commit 1592584 from Michael McCandless in branch 'dev/branches/lucene_solr_4_8'\n[ https://svn.apache.org/r1592584 ]\n\nLUCENE-5599, LUCENE-5600, LUCENE-5628: backport to 4.8.x ",
            "date": "2014-05-05T17:43:56+0000"
        }
    ]
}