{
    "id": "SOLR-482",
    "title": "Error handling in CSVLoader",
    "details": {
        "affect_versions": "None",
        "status": "Closed",
        "fix_versions": [
            "3.1",
            "4.0-ALPHA"
        ],
        "components": [
            "update"
        ],
        "type": "Improvement",
        "priority": "Minor",
        "labels": "",
        "resolution": "Fixed"
    },
    "description": "Sometimes the underlying CSV parser can't read a line and throws an exception.  Solr currently just passes the exception out to the client.  Wrapping this in a SolrException allows us to pass out information about what line failed (which isn't always in the CSV IOException thrown).",
    "attachments": {
        "SOLR-482.patch": "https://issues.apache.org/jira/secure/attachment/12375937/SOLR-482.patch"
    },
    "issue_links": {},
    "comments": [
        {
            "author": "Grant Ingersoll",
            "id": "comment-12570293",
            "date": "2008-02-19T16:27:15+0000",
            "content": "Adds a new input_err method that is called when an IOException is caught by readLine() method. "
        },
        {
            "author": "Grant Ingersoll",
            "id": "comment-12986482",
            "date": "2011-01-25T16:14:09+0000",
            "content": "Working through some old patches, this one is pretty tame and gives a little more info when an error is encountered than it used to.  Will commit shortly. "
        },
        {
            "author": "Grant Ingersoll",
            "id": "comment-12986519",
            "date": "2011-01-25T17:02:23+0000",
            "content": "committed on trunk and 3.x "
        },
        {
            "author": "Grant Ingersoll",
            "id": "comment-13013165",
            "date": "2011-03-30T15:45:45+0000",
            "content": "Bulk close for 3.1.0 release "
        }
    ]
}