{
    "id": "SOLR-2422",
    "title": "Improve reliability of ZkSolrClientTest",
    "details": {
        "affect_versions": "4.0-ALPHA",
        "status": "Open",
        "fix_versions": [],
        "components": [
            "Build"
        ],
        "type": "Bug",
        "priority": "Major",
        "labels": "",
        "resolution": "Unresolved"
    },
    "description": "The ZKSolrClient test is pretty unreliable, it seems to fail a significant portion of the time on hudson (often on my local as well).\n\nAdditionally it seems to somehow sometimes (maybe depending upon retry loop?) leave a lot of zookeeper threads running.\n\nI ran into these issues when i discovered that trying to interrupt() these threads after the test completed was triggering a JRE bug, but by working through it I saw how unreliable the test is.",
    "attachments": {},
    "issue_links": {},
    "comments": [
        {
            "author": "Robert Muir",
            "id": "comment-13005975",
            "date": "2011-03-12T02:24:39+0000",
            "content": "The first problem I found here is in testConnect, it has a timeout of 100ms\n\nOur lucene slave is pretty busy (lots of cores, so lots of tests going on at once in parallel).\n\nBy changing this timeout to AbstractZkTestCase.TIMEOUT (10000ms), I found the test to be significantly more reliable. This is consistent with the other test cases, they seem to use this timeout.\n\nI tested this on hudson and it seems a big improvement, so I committed the trivial change in r1080852 (sorry for the heavy-commit, I know we are all sick of the hudson instability). "
        },
        {
            "author": "Robert Muir",
            "id": "comment-13005976",
            "date": "2011-03-12T02:38:35+0000",
            "content": "There's definitely something up with the exception message here, but maybe something else going on with reconnection or similar?\n\nBecause I noticed when the test failed before with the 100ms timeout, it would print:\n\n1 tests failed.\nFAILED:  org.apache.solr.cloud.ZkSolrClientTest.testConnect\n\nError Message:\nCould not connect to ZooKeeper 127.0.0.1:30762/solr within 30000 ms\n\n\n\nI think this is what made it hard to debug problems, it made me think it was actually waiting 30000ms, but in fact was only waiting 100ms.\n\nLooking at ConnectionManager, I think this might indicate a bug (at least in the exception message, but the use of \"two timeouts\" seems wrong)... i added my comments to the source snippet:\n\n\ntry {\n        // zkClientTimeout = 100ms\n        connectionStrategy.reconnect(zkServerAddress, zkClientTimeout, this, new ZkClientConnectionStrategy.ZkUpdate() {\n          @Override\n          public void update(SolrZooKeeper keeper) throws InterruptedException, TimeoutException, IOException {\n           // DEFAULT_CLIENT_CONNECT_TIMEOUT = 30000ms\n           waitForConnected(SolrZkClient.DEFAULT_CLIENT_CONNECT_TIMEOUT);\n           client.updateKeeper(keeper);\n           if(onReconnect != null) {\n             onReconnect.command();\n           }\n           ConnectionManager.this.connected = true;\n          }\n        });\n      } catch (Exception e) {\n        log.error(\"\", e); // fails after 100ms, but says it waited 30000ms?!\n      }\n\n "
        }
    ]
}