{
    "id": "SOLR-2504",
    "title": "Combined usage of Synonyms/SpellChecker causes java.lang.NullPointerException, when searching for a word out of synonyms.txt",
    "details": {
        "affect_versions": "3.1",
        "status": "Closed",
        "fix_versions": [],
        "components": [
            "clients - java",
            "spellchecker"
        ],
        "type": "Bug",
        "priority": "Major",
        "labels": "",
        "resolution": "Fixed"
    },
    "description": "After migrating from 1.4 to 3.1 we experience the following behaviour:\n\nWhen SpellChecking is turned off, everything works fine.\nWhen Synonyms are not being used, everything works fine.\n\nWhen both, SpellChecking and Synonyms, are being used and a search is triggered, that contains at least one of the words out of synonyms.txt the following error is thrown:\n\njava.lang.NullPointerException\n        at org.apache.lucene.util.AttributeSource.cloneAttributes(AttributeSource.java:542)\n        at org.apache.solr.analysis.SynonymFilter.incrementToken(SynonymFilter.java:132)\n        at org.apache.lucene.analysis.FilteringTokenFilter.incrementToken(FilteringTokenFilter.java:58)\n        at org.apache.solr.handler.component.SpellCheckComponent.getTokens(SpellCheckComponent.java:485)\n        at org.apache.solr.handler.component.SpellCheckComponent.process(SpellCheckComponent.java:131)\n        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:194)\n        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)\n        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1360)\n        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:356)\n        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:252)\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)\n        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)\n        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:172)\n        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)\n        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)\n        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)\n        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:151)\n        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:874)\n        at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)\n        at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)\n        at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)\n        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)\n        at java.lang.Thread.run(Thread.java:619)\n\nThe problem has been described already here:\nhttp://osdir.com/ml/solr-user.lucene.apache.org/2010-09/msg00945.html\n\nI have a report of a third person, experiencing the same problem.",
    "attachments": {},
    "issue_links": {},
    "comments": [
        {
            "author": "Uwe Schindler",
            "id": "comment-13030675",
            "date": "2011-05-09T10:28:07+0000",
            "content": "The line numbers in your stack trace do not correspond to the officially released version 3.1 of Lucene 3.1 / Solr 3.1. Maybe you have some older JAR files in your classpath? "
        },
        {
            "author": "Jens Bertheau",
            "id": "comment-13030678",
            "date": "2011-05-09T10:40:44+0000",
            "content": "Updated: In my first posting I pasted the error message with wrong line numbers, now the line numbers should represent the current JAR files. "
        },
        {
            "author": "Uwe Schindler",
            "id": "comment-13030681",
            "date": "2011-05-09T10:54:59+0000",
            "content": "Thanks for the correct line numbers! My last comment I deleted was wrong.\n\nIn the current stable branch there is an update related to that, maybe take the current stable branch? "
        },
        {
            "author": "Stefan Moises",
            "id": "comment-13030684",
            "date": "2011-05-09T11:11:09+0000",
            "content": "I am the initial reporter of this bug in the mailing list and currently we are using a nightly build of Solr (apache-solr-4.0-2011-03-16_08-16-50.tar) and still get the error, so I don't think it has been fixed yet, unless those changes you've mentioned have been at a later date or in another branch - here are my line numbers from that nighly build:\n\nSEVERE: java.lang.NullPointerException\n        at org.apache.lucene.util.AttributeSource.cloneAttributes(AttributeSource.java:507)\n        at org.apache.lucene.analysis.synonym.SynonymFilter.incrementToken(SynonymFilter.java:131)\n        at org.apache.lucene.analysis.util.FilteringTokenFilter.incrementToken(FilteringTokenFilter.java:60)\n        at org.apache.lucene.analysis.miscellaneous.WordDelimiterFilter.incrementToken(WordDelimiterFilter.java:224)\n        at org.apache.lucene.analysis.core.LowerCaseFilter.incrementToken(LowerCaseFilter.java:54)\n        at org.apache.lucene.analysis.miscellaneous.KeywordMarkerFilter.incrementToken(KeywordMarkerFilter.java:76)\n        at org.apache.lucene.analysis.snowball.SnowballFilter.incrementToken(SnowballFilter.java:77)\n        at org.apache.lucene.analysis.miscellaneous.RemoveDuplicatesTokenFilter.incrementToken(RemoveDuplicatesTokenFilter.java:54)\n        at org.apache.solr.spelling.SpellingQueryConverter.convert(SpellingQueryConverter.java:115)\n        at org.apache.solr.handler.component.SpellCheckComponent.process(SpellCheckComponent.java:137)\n        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:239)\n        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)\n        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1298)\n        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:353)\n        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:248)\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)\n        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)\n        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:465)\n        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)\n        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)\n        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:555)\n        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)\n        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)\n        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:852)\n        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)\n        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)\n        at java.lang.Thread.run(Thread.java:662) "
        },
        {
            "author": "Uwe Schindler",
            "id": "comment-13030685",
            "date": "2011-05-09T11:12:43+0000",
            "content": "From looking at the code: It's impossible to get an NPE at this place. As this bug only appears in some combinations of components in Solr, this maybe an Hotspot bug in Suns JVM. Can you try to run your server using the -Xbatch switch, to disable background hotspot compilation (may slowdown your server immense)? "
        },
        {
            "author": "Uwe Schindler",
            "id": "comment-13030686",
            "date": "2011-05-09T11:14:55+0000",
            "content": "Stefan Moises: Changes in AttributeSource are dated 2011-04-23 (LUCENE-3042). "
        },
        {
            "author": "Stefan Moises",
            "id": "comment-13030719",
            "date": "2011-05-09T13:03:41+0000",
            "content": "Uwe: thanks for the info! Would it make sense to update to the latest nightly? But I'm with you, the code doesn't look like there should ever be a NPE ... So I'll try the JVM switch first I think. "
        },
        {
            "author": "Jens Bertheau",
            "id": "comment-13030722",
            "date": "2011-05-09T13:19:03+0000",
            "content": "OK, I tried the current snapshot (1100496) and it actually solves the problem!\n@Stefan: Apparently you are using already Solr 4. Not sure, if the problem has been fixed in the 4-branch... "
        },
        {
            "author": "Uwe Schindler",
            "id": "comment-13030730",
            "date": "2011-05-09T13:42:11+0000",
            "content": "Its also fixed in trunk since the above date! "
        },
        {
            "author": "Stefan Moises",
            "id": "comment-13030744",
            "date": "2011-05-09T14:09:17+0000",
            "content": "Awesome, I'll update ASAP and let you know if everythings ok in Solr 4.x now, too! "
        },
        {
            "author": "Jens Bertheau",
            "id": "comment-13030763",
            "date": "2011-05-09T15:09:32+0000",
            "content": "Fixed in version of 2011-04-23 "
        },
        {
            "author": "Stefan Moises",
            "id": "comment-13031396",
            "date": "2011-05-10T21:36:53+0000",
            "content": "Just for the record - works now for me in trunk, too! Many thanks for the quick help! "
        },
        {
            "author": "Uwe Schindler",
            "id": "comment-13031436",
            "date": "2011-05-10T22:33:59+0000",
            "content": "Can we close this issue then? The reason for this problem is still unknown, I suspect an JVM bug, because NPE is impossible at that point. The changes in code simply removed the problem - but I don't understand why.\n\nCan we confirm that it works with current updated 3.1 branch, future 3.2 (branch_3x) and 4.0 (trunk)? "
        }
    ]
}