{
    "id": "SOLR-7990",
    "title": "timeAllowed is returning wrong results on the same query submitted with different timeAllowed limits",
    "details": {
        "components": [],
        "type": "Bug",
        "labels": "",
        "fix_versions": [
            "5.3.1"
        ],
        "affect_versions": "5.2.1,                                            5.4,                                            6.0",
        "status": "Resolved",
        "resolution": "Fixed",
        "priority": "Major"
    },
    "description": "William Bell raised a question on the user's list. The scenario is\n> send a query that exceeds timeAllowed\n> send another identical query with larger timeAllowed that does NOT time out\n\nThe results from the second query are not correct, they reflect the doc count from the first query.\n\nIt apparently has to do with filter queries being inappropriately created and re-used. I've attached a test case that illustrates the problem.\n\nThere are three tests here. \ntestFilterSimpleCase shows the problem.\n\ntestCacheAssumptions is my hack at what I think the states of the caches should be, but has a bunch of clutter so I'm Ignoring it for now. This should be un-ignored and testFilterSimpleCase removed when there's any fix proposed. The assumptions may not be correct though.\n\ntestQueryResults shows what I think is a problem, the second call that does NOT exceed timeAllowed still reports partial results.",
    "attachments": {
        "SOLR-7990.patch": "https://issues.apache.org/jira/secure/attachment/12753154/SOLR-7990.patch",
        "SOLR-7990_filterFix.patch": "https://issues.apache.org/jira/secure/attachment/12754010/SOLR-7990_filterFix.patch"
    },
    "issue_links": {},
    "comments": [
        {
            "date": "2015-08-29T22:24:51+0000",
            "author": "Erick Erickson",
            "content": "Failing test cases, no fixes though. ",
            "id": "comment-14721277"
        },
        {
            "date": "2015-08-30T15:13:57+0000",
            "author": "Erick Erickson",
            "content": "testQueryResults was a bad test, didn't test for null so that test was inappropriately failing when looking for partial results after the second search ",
            "id": "comment-14721558"
        },
        {
            "date": "2015-09-03T15:51:19+0000",
            "author": "Yonik Seeley",
            "content": "Here's a patch that should fix the filter issue.\n\nThe bad code was in getDocSetNC (I have since moved that code to DocSetUtil) that caught the exception and logged a warning but did nothing else.\n\nSince we don't know the context that the DocSet will be used in, we can't catch the exception there.  It may be cached later.  It may even be negated - there are multiple places this can happen, such as a pure-negative filter query.  In that case, terminating early could result in matching documents that would otherwise have never matched!\n\nHere's a simple match removing the exception swallow.\n\nedit: this isn't a complete patch - I haven't run tests, and I don't know if this breaks other tests. ",
            "id": "comment-14729300"
        },
        {
            "date": "2015-09-03T16:00:08+0000",
            "author": "Erick Erickson",
            "content": "Yonik Seeley Cool, I just assigned it to myself to not lose track it, wasn't going to be getting around to it for a while. Want me to run with it? ",
            "id": "comment-14729313"
        },
        {
            "date": "2015-09-03T16:04:58+0000",
            "author": "Yonik Seeley",
            "content": "Yeah sure, I was just running the full tests, and it does look like some fail now.  Not sure if it's a test bug or if we're missing a high level catch of this exception... ",
            "id": "comment-14729318"
        },
        {
            "date": "2015-09-03T17:35:49+0000",
            "author": "Erick Erickson",
            "content": "I don't particularly have any investment in owning this, mostly volunteering to do the scutwork...... ",
            "id": "comment-14729442"
        },
        {
            "date": "2015-09-03T19:59:32+0000",
            "author": "Erick Erickson",
            "content": "The test I added for this condition still fails though for a start.. testSimpleFilterCase... ",
            "id": "comment-14729680"
        },
        {
            "date": "2015-09-08T16:54:10+0000",
            "author": "Yonik Seeley",
            "content": "This patch makes all the tests pass and should fix the issue with a partial filter being cached.\n\nStill needs a test that fails w/o it though.  I'll also try to look at why your test fails. ",
            "id": "comment-14735144"
        },
        {
            "date": "2015-09-08T17:46:41+0000",
            "author": "Yonik Seeley",
            "content": "Actually, I may just try to rewrite the ExitableDirectoryReaderTest, as that test uses no caches and hence can't test if it's caching any partial results. ",
            "id": "comment-14735256"
        },
        {
            "date": "2015-09-08T18:01:38+0000",
            "author": "Erick Erickson",
            "content": "Right, I ripped this test off ExitableDirectoryReaderTest just to get a fast-n-dirty isolation of the issue, see the nocommit comments .\n\nSo yeah, piggy-backing this off ExitableDirectoryTest seems like A Good Thing. ",
            "id": "comment-14735291"
        },
        {
            "date": "2015-09-08T18:43:56+0000",
            "author": "Yonik Seeley",
            "content": "Here's the latest patch with the rewritten ExitableDirectoryReaderTest.  It fails without the patch and passes with it. ",
            "id": "comment-14735368"
        },
        {
            "date": "2015-09-08T19:02:51+0000",
            "author": "Yonik Seeley",
            "content": "OK, I figured out why your test was failing... there were no name:a* docs because you overwrote them all with name:b* docs in createIndex  ",
            "id": "comment-14735415"
        },
        {
            "date": "2015-09-08T21:16:42+0000",
            "author": "Erick Erickson",
            "content": "Seems I'm the statue more often than the pigeon lately....\n\nassertU(adoc(\"id\", Integer.toString(idx), \"name\", \"b\" + idx + NUM_DOCS));\n\nshould have been\n\nassertU(adoc(\"id\", Integer.toString(idx + NUM_DOCS), \"name\", \"b\" + idx));\n\nOops. ",
            "id": "comment-14735628"
        },
        {
            "date": "2015-09-08T21:37:16+0000",
            "author": "Yonik Seeley",
            "content": "I'm working on test fixes... my test changes were no good since the timeAllowed does not include query parsing time (which is where the time goes in the sleep function). ",
            "id": "comment-14735666"
        },
        {
            "date": "2015-09-08T23:02:10+0000",
            "author": "Yonik Seeley",
            "content": "Here's the final patch.\nI also incorporated parts of Erick's test and modified the delay component to take a parameter that tells it how long to sleep. ",
            "id": "comment-14735788"
        },
        {
            "date": "2015-09-09T02:49:11+0000",
            "author": "Yonik Seeley",
            "content": "Oops, forgot to take care of the cloud version of the test.  Here's another patch. ",
            "id": "comment-14736040"
        },
        {
            "date": "2015-09-09T14:00:44+0000",
            "author": "ASF subversion and git services",
            "content": "Commit 1702015 from Yonik Seeley in branch 'dev/trunk'\n[ https://svn.apache.org/r1702015 ]\n\nSOLR-7990: don't swallow ExitingReaderException ",
            "id": "comment-14736889"
        },
        {
            "date": "2015-09-09T14:03:00+0000",
            "author": "ASF subversion and git services",
            "content": "Commit 1702016 from Yonik Seeley in branch 'dev/branches/branch_5x'\n[ https://svn.apache.org/r1702016 ]\n\nSOLR-7990: don't swallow ExitingReaderException ",
            "id": "comment-14736897"
        },
        {
            "date": "2015-09-09T14:20:44+0000",
            "author": "Yonik Seeley",
            "content": "Merging back to 5.3.1 had conflicts, so needed some backport... running full tests now. ",
            "id": "comment-14736924"
        },
        {
            "date": "2015-09-09T15:04:44+0000",
            "author": "ASF subversion and git services",
            "content": "Commit 1702037 from Yonik Seeley in branch 'dev/branches/lucene_solr_5_3'\n[ https://svn.apache.org/r1702037 ]\n\nSOLR-7990: don't swallow ExitingReaderException ",
            "id": "comment-14736998"
        }
    ]
}